[package]
name = "winnow-grammar"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["winnow-grammar-macro"]

[dependencies]
winnow-grammar-macro = { path = "winnow-grammar-macro", version = "0.1.0" }
winnow = "0.6"
syn-grammar = { version = "0.4.0", path = "../syn-grammar" }
