[workspace]
members = ["winnow-grammar-macro"]
resolver = "2"

[package]
name = "winnow-grammar"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = "0.6"
winnow-grammar-macro = { path = "winnow-grammar-macro" }
syn-grammar = { version = "0.4.0", path = "../syn-grammar" }
